version: "2.1"
services:
  gluetun:
    image: qmcgaw/gluetun
    cap_add:
      - NET_ADMIN
    ports:
      - 9696:9696
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
      - 8080:8080
    environment:
      - VPN_SERVICE_PROVIDER=nordvpn
      - VPN_TYPE=wireguard # or wireguard
      - SERVER_COUNTRIES=Germany
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
    volumes:
      - ./prowlarr:/config
    network_mode: "service:gluetun"
    restart: unless-stopped

  transmission:
    image: linuxserver/transmission
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
    volumes:
      - ./transmission:/config
      - /media/transmission/downloads:/downloads
    network_mode: "service:gluetun"
    restart: unless-stopped

  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./sabnzbd:/config
      - /media/sabnzbd/downloads:/downloads #optional
      - /media/sabnzbd/incomplete/downloads:/incomplete-downloads #optional
    network_mode: "service:gluetun"
    restart: unless-stopped